import VersoSlides
import VersoBlueprint.Graft
import VersoBlueprint.Slides
import Verso.Doc.Concrete
import Lib.Widgets

open VersoSlides

set_option verso.code.warnLineLength 100

#doc (Slides) "Verso Blueprint: Reimagining Blueprints for the AI Era" =>

# Verso Blueprint: Reimagining Blueprints for the AI Era

[Emilio Jesús Gallego Arias](https://x80.org/emilio)

Senior Research Engineer — Lean FRO

ForMath Seminar, IRIF, Université Paris Cité

Monday, 21 September 2026

# AI Is Changing Mathematics

%%%
vertical := some true
%%%

:::hstack

- AI systems are producing *serious mathematics*.
- Mathematicians need ways to _inspect_, _guide_, and _trust_ the process.
- _Mathematical output_ now includes *complex artifacts* that are hard to digest.
- Mathematics and computer science are facing a _hard_ challenge.

{image "static/images/slide_1.1_erdos.png"}[Erdos' Unit Problem Solution Tweet by Timothy Gowers]

:::

*Timothy Gowers*:

> "If you are a mathematician, then you may want to make sure you are sitting down before reading further."


## Sphere Packing In Dimension Eight

::::vstack

{arxiv "2604.23468" (title := "A Milestone in Formalization: The Sphere Packing Problem in Dimension 8") (authors := "Hariharan, Birkbeck, Lee, Ma, Mehta, Poiroux, Viazovska") (published := "Submitted Apr 25, 2026; v2 Apr 28, 2026") (summary := "The dimension-8 sphere-packing result was formally verified in February 2026, with final stages carried out by Math Inc.'s Gauss model.")}

:::center
{image "static/images/math_inc_2.png"}[Math Inc announcement of the formalization]
:::

::::

## The Sphere Packing Blueprint

:::::vstack

Auto-formalization crucially relied on a pre-existing Blueprint, and filled the gaps.

::::class "sphere-images"
:::hstack

{image (width := "95%") "static/images/sp_index.png"}[Sphere-packing blueprint start page]

{image (width := "95%") "static/images/sp_graph.png"}[Sphere-packing blueprint graph]

:::
::::

*The Blueprint seems essential, but how can we measure its importance?*

:::::


## Fermat's Last Theorem: Scale

::::hstack

:::class "milestone-stat"
*13 million* Lean lines
:::

:::class "milestone-stat"
*30,300* theorems proved
:::

::::

Anthropic completed a [Lean formalization of FLT](https://www.anthropic.com/research/formalizing-fermats-last-theorem), following the Darmon–Diamond–Taylor exposition.

```html
<video class="flt-progress-video" src="flt-progress.mp4" poster="flt-progress-poster.png" muted loop playsinline controls preload="metadata" aria-label="Time progression of Anthropic's FLT formalization"></video>
```

*How do we handle a proof of this size?*


## FLT: The Plan Behind The Proof

:::class "flt-opening-quote"
Anthropic: “... agents quickly lost track of the project’s state and stopped collaborating effectively.”
:::

:::class "flt-plan-image"
{image (width := "100%") "static/images/flt-plan.png"}[Anthropic's Prove2Me plan showing the Mazur, Ribet, and Wiles branches leading to FLT]
:::

:::class "flt-solution-quote"
Anthropic: “The effort succeeded when we switched to using Prove2Me”
:::

:::class "flt-functions"
- A theorem DAG kept tasks and dependencies visible.
- Separate statement and proof files made compilation cheaper.
- Natural-language descriptions made theorems easier to find and reuse.
:::


## Where is mathematics going?

:::class "math-direction-event"
*2 June 2026 · [Leiden Declaration](https://leidendeclaration.ai/)*
Mathematical practice in the age of AI agents.
:::

:::class "math-direction-event"
*4 September 2026 · [Anthropic's FLT formalization](https://www.anthropic.com/research/formalizing-fermats-last-theorem)*
Pushed the frontier on what's possible autonomously.
:::

:::class "math-direction-event"
*11 September 2026 · [A Severe Misalignment of AI in Mathematics](https://mathandai.org/)*
Do AI startups' incentives harm mathematical practice?
:::

:::class "math-direction-response"
[SAIR's open models initiative](https://sair.foundation/open-math-model/) argues for tools the community can inspect and shape, independent of market constraints.
:::

:::class "math-direction-conclusion"
We must provide tools to help address these issues and smooth human/agent interaction.
:::


# Blueprint: Historical Context

%%%
vertical := some true
%%%

:::::vstack

- *Feit-Thompson Theorem (~2010)*: Custom system to track progress, generated by CI
- *Flyspeck (~2010)*: _Mathwiki_

Large-scale formal developments pose many coordination and alignment challenges.

:::hal "hal-00816699" (title := "A Machine-Checked Proof of the Odd Order Theorem") (authors := "Gonthier, Asperti, Avigad, Bertot, Cohen, Garillot, Le Roux, Mahboubi, O'Connor, Ould Biha, Pasca, Rideau, Solovyev, Tassi, Thery") (published := "Submitted to HAL Apr 22, 2013") (venue := "ITP 2013, LNCS 7998, pp. 163-179") (url := "https://hal.inria.fr/hal-00816699") (pdf := "https://www.msr-inria.fr/files/hal-00816699/file/main.pdf")
The paper reports the machine-checked formal proof of the Feit-Thompson Odd
Order Theorem in Coq/Rocq, built on the Mathematical Components library.
:::

:::::

## LeanBlueprint

::::class "leanblueprint-history"

- Created by [Patrick Massot](https://www.imo.universite-paris-saclay.fr/~patrick.massot/)
  for [sphere eversion](https://leanprover-community.github.io/sphere-eversion/) (2020),
  then used for the Liquid Tensor Experiment.
- [LeanBlueprint](https://github.com/PatrickMassot/leanblueprint) extends
  LaTeX/plasTeX with dependencies, graph rendering, and formalization status.
- Widely used and very influential across Lean projects; it is our starting point.

:::class "leanblueprint-graph"
{image "static/images/lte2.png"}[Liquid Tensor Experiment Blueprint dependency graph]
:::

::::

## Why Build Verso Blueprint?

*Why VBP when LeanBlueprint already exists?*

We start from LeanBlueprint's model of nodes, graphs, progress, and links to Lean.

- *Lean-native authoring*: prose, checked examples, and extensions in one development environment.
- *Improved data analysis*: derive progress and dependencies from Lean code, as pioneered by [LeanArchitect](https://arxiv.org/abs/2601.22554).
- *Principled API*: an open system designed to integrate through typed Lean APIs.


# Verso: Documentation as a Lean DSL

%%%
vertical := some true
%%%

```html
<video class="verso-talk-video" src="verso-documentation-dsl.mp4" poster="verso-dsl-poster.png" controls preload="metadata" aria-label="David Thrane Christiansen: Verso: Documentation as a DSL"></video>
```

[Verso: written in Lean, checked by Lean](https://verso.lean-lang.org/)

[David Thrane Christiansen, Lean Together 2024](https://www.youtube.com/watch?v=dv_vmVs3SQQ)

Verso addresses recurring markup-language problems:

- *Extensibility*: imported Lean modules add syntax and elaboration.
- *Integration*: prose, Lean code, and tools share one build and environment.
- *Semantics*: elaboration produces structured data before rendering.


## A Verso Document: Source And Output

::::::class "verso-complete-document"
:::::hstack

::::class "verso-document-source"
:::vstack
*Verso source* (imports omitted)

````code verso
#doc (Manual) "Equality transport" =>
# Applying a function
%%%
tag := "transport"
%%%
If $`x = y`, then $`g(x) = g(y)`.
The Lean declaration is {name}`congrArg`.

```lean
example (g : Nat → Nat) (x y : Nat)
    (h : x = y) : g x = g y := by
  exact congrArg g h
```

Return to {ref "transport"}[applying a function].
````
:::
::::

::::class "verso-document-result"
:::vstack
*Generated Manual page*

{image (width := "100%") "static/webshots/verso-equality-transport.png"}[Generated Applying a function page with the matching checked proof, congrArg declaration reference, and document link]

[Explore the document](demo/verso/Applying-a-function/)
:::
::::
:::::
::::::

:::class "verso-document-takeaway"
*Lean checks document well-formedness* `{name}`: must be a Lean declaration · `{ref}`: must be a document target.
:::


## Two Phases Of A Verso Build

```diagram (background := "#ffffff")
open Illuminate Lean in
let ink := rgb!"#1e293b"
let teal := rgb!"#007da5"
let muted := rgb!"#64748b"
let txt (s : String) (size : Float := 13) (bold := false) : Diagram SVG :=
  Diagram.text s { fontSize := size, fontFamily := "sans-serif", color := ink, bold }
let box (name : Name) (label : String) (fill : Color) : Diagram SVG :=
  txt label
    |>.padXY 12 9
    |>.filledFrame (fill := fill) (stroke := { color := muted, width := 1.2 })
    |>.namedWithAnchors name
let chapter := box `chapter "Chapter.olean\nroles and directives" (rgb!"#f8fafc")
  |>.translate (-420) 115
let glossary := box `glossary "Glossary.olean\ntargets and references" (rgb!"#f8fafc")
  |>.translate (-420) 0
let extension := box `extension "Extension.olean\ncustom elaborators" (rgb!"#f8fafc")
  |>.translate (-420) (-115)
let environment := box `environment "Document environment\nenvironment extensions" (rgb!"#ecfeff")
let build := box `build "Verso document pass\ncollect, resolve, render" (rgb!"#e0f2fe")
  |>.translate 270 0
let output := box `output "Rendered document\nHTML, PDF, or slides" (rgb!"#f0fdf4")
  |>.translate 535 0
let ah : Arrowhead := { type := .stealth }
chapter.compose glossary |>.compose extension |>.compose environment |>.compose build |>.compose output
  |>.connect `chapter.east `environment.west (arrowhead := ah)
    (stroke := { color := muted, width := 1.1, dash := .dashed })
  |>.connect `glossary.east `environment.west (arrowhead := ah)
    (stroke := { color := muted, width := 1.1, dash := .dashed })
  |>.connect `extension.east `environment.west (arrowhead := ah)
    (stroke := { color := muted, width := 1.1, dash := .dashed })
  |>.connect `environment.east `build.west (arrowhead := ah)
    (stroke := { color := teal, width := 1.6 })
  |>.connect `build.east `output.west (arrowhead := ah)
    (stroke := { color := teal, width := 1.6 })
  |>.scale 0.82
```

*Phase 1 — Lean elaboration:* modules contribute document data through
environment extensions, persisted in `.olean` files.

*Phase 2 — document generation:* Verso collects the final environment,
resolves references, and renders the selected genre.


## Extension Points: Roles, Directives, And Code Blocks

:::::class "verso-extension-points"
::::hstack

:::vstack

*Roles* are inline.

```code verso
The Lean declaration is {name}`congrArg`.
```

They can resolve a target, register a reference, or render an interactive
inline object.

:::

:::vstack

*Directives* are block-level.

```code verso
:::theorem "left_inverse_injective"
A function admitting a left inverse is injective.
:::
```

They can introduce structure, metadata, and rich rendered blocks.

:::

:::vstack

*Code blocks* elaborate Lean.

```lean -panel
example : 1 + 1 = 2 := rfl
```

They can type-check code, expose proof states, and contribute semantic data.

:::

::::
:::::

The extension author defines what each elaboration does: *emit typed data*,
*report diagnostics*, *render a node*, or *combine these effects*.


# Verso Blueprint Architecture

%%%
vertical := some true
%%%

[https://github.com/leanprover/verso-blueprint](https://github.com/leanprover/verso-blueprint)

:::hstack

- Directly inspired by [LeanBlueprint](https://github.com/PatrickMassot/leanblueprint), [LeanArchitect](https://arxiv.org/abs/2601.22554), and Side to Side
- *Core model written in Lean*: labels, nodes, metadata, code links, status
- *Document layer in Verso*: rich, extensible markup and interactive output
- Coherent data is used in graphs, summaries, previews, slides, and tools

{image (width := "96%") "static/images/vbp-architecture.svg"}[Verso Blueprints architecture diagram]

:::

## A Theorem In Verso Blueprint

:::class "theorem-source"
````code verso
:::theorem "left_inverse_injective"
    (uses := "left_inverse, injective")
    (owner := "presenter") (tags := "functions, demo")
A function admitting a left inverse is injective.
:::

```lean "left_inverse_injective" (autoDeps := true)
theorem leftInverseInjective (f g : Nat → Nat)
    (hgf : LeftInverse f g) : Injective f := by
  intro x y h
  exact (hgf x).symm.trans ((transportEq g h).trans (hgf y))
```

:::proof "left_inverse_injective" (uses := "equality_transport")
Apply g to the equality, then use the left-inverse identity.
:::
````
:::

The label `left_inverse_injective` connects the mathematical statement, Lean declaration, and proof.


## The Rendered Theorem

{demoFrame "demo/after/panel.html?slide=1" "Rendered left-inverse theorem"}


## Reading A Node: The Frey Curve

{blueprint_node "FreyCurve" (siteBase := "blueprint")}


## The Dependency Graph

{blueprintGraph (view := "full") (class := "flt-graph-frame")}

[Open the FLT progress summary](blueprint/Blueprint-Summary/)


## Code-First Authoring

Inspired by [LeanArchitect](https://arxiv.org/abs/2601.22554), we also support attribute-based annotations.

```code lean
/-- Applying a function preserves equality. -/
@[blueprint "equality_transport"]
theorem transportEq (g : Nat → Nat) {a b : Nat} (h : a = b) :
    g a = g b := congrArg g h
```

Here `@[blueprint]` associates `transportEq` with the `equality_transport` node.

Prose elsewhere can contribute more data (for example statement and proof text) under the same label.

Use `(lean := "Existing.declaration")` to attach an existing compiled declaration to a Blueprint node.


## More Verso Blueprint Features

- *Statements and proofs*: write the mathematics in prose and attach checked Lean code.
- *Dependencies*: declare them explicitly or extract them from Lean, separately for statements and proofs.
- *Sources*: connect the original text, the informal account, and the formal declarations.
- *Project organization*: group nodes, assign owners, and record tags, effort, and priority.
- *Progress*: see what is formalized and which statements or proofs are ready to work on.
- *Tools*: display the same nodes in documents and graphs, or query them through the CLI and API.


## Validation

A key challenge was validating large Verso-based blueprints.

We built the [leanblueprint-to-verso harness](https://github.com/ejgallego/leanblueprint-to-verso) to guide AI-assisted translation from TeX to Verso.

- [Kevin Buzzard’s FLT blueprint](https://github.com/ejgallego/verso-flt)
- [Sphere Packing](https://github.com/ejgallego/verso-sphere-packing)
- [Carleson Operators on Doubling Metric Measure Spaces](https://github.com/ejgallego/verso-carleson), by Floris van Doorn
- [Noperthedron](https://github.com/ejgallego/verso-noperthedron), by David Renshaw and Jason Reed

The harness checks document structure and Lean links. Its text similarity
scores compare paired source and translation blocks to guide human review.

[Open the translation review interface](https://x80.org/flt-translation-review/)


# What's next? Towards "Programmatic blueprints"

%%%
vertical := some true
%%%

:::class "whats-next-intro"
Verso Blueprint's goal is to provide core document infrastructure for mathematical research projects. In particular, we want to support hybrid human-agent loops that interact with Verso documents in several ways:
:::

:::class "programmatic-goals"
- A stable record of mathematical statements, dependencies, sources, project state, all available through queries.
- Define tools, not *policy*: our goal is to make it easy for users and agents to organize _as they want_.
- Hopefully helpful for projects such as [Prove2Me](https://prove2.me/), [Trellis](https://www.math.cmu.edu/~wes/trellis.php), and [AutoformBot](https://github.com/facebookresearch/autoform-bot).
:::


## Roadmap · September–December 2026

:::class "roadmap-timeline"
```diagram (background := "#ffffff")
open Illuminate Lean in
let ink := rgb!"#1e293b"
let teal := rgb!"#007da5"
let blue := rgb!"#2563eb"
let muted := rgb!"#64748b"
let txt (s : String) (size : Float := 16) (bold := false) (color := ink) : Diagram SVG :=
  Diagram.text s { fontSize := size, fontFamily := "sans-serif", color, bold }
let item (x y : Float) (first second : String) : Diagram SVG :=
  Diagram.vsep 4 [txt first 16 true, txt second 16 true]
    |>.translate x y
let axis : Diagram SVG :=
  Diagram.line ⟨-460, 0⟩ ⟨460, 0⟩ { color := muted, width := 2 }
let marks : Diagram SVG :=
  (Diagram.circle 7 (fill := teal) |>.translate (-430) 0)
    |>.compose (Diagram.circle 7 (fill := blue) |>.translate (-258) 0)
    |>.compose (Diagram.circle 7 (fill := teal) |>.translate (-86) 0)
    |>.compose (Diagram.circle 7 (fill := blue) |>.translate 86 0)
    |>.compose (Diagram.circle 7 (fill := teal) |>.translate 258 0)
    |>.compose (Diagram.circle 7 (fill := blue) |>.translate 430 0)
let stems : Diagram SVG :=
  Diagram.line ⟨-430, 8⟩ ⟨-430, 39⟩ { color := teal, width := 1.5 }
    |>.compose (Diagram.line ⟨-258, -8⟩ ⟨-258, -39⟩ { color := blue, width := 1.5 })
    |>.compose (Diagram.line ⟨-86, 8⟩ ⟨-86, 39⟩ { color := teal, width := 1.5 })
    |>.compose (Diagram.line ⟨86, -8⟩ ⟨86, -39⟩ { color := blue, width := 1.5 })
    |>.compose (Diagram.line ⟨258, 8⟩ ⟨258, 39⟩ { color := teal, width := 1.5 })
    |>.compose (Diagram.line ⟨430, -8⟩ ⟨430, -39⟩ { color := blue, width := 1.5 })
axis.compose stems |>.compose marks
  |>.compose (item (-430) 77 "Formal Database" "Model")
  |>.compose (item (-258) (-77) "Improved" "Skill")
  |>.compose (item (-86) 77 "Improved Verso" "Performance")
  |>.compose (txt "Widget" 16 true |>.translate 86 (-77))
  |>.compose (item 258 77 "Side-by-Side" "analysis")
  |>.compose (item 430 (-77) "Direct agentic" "loop support")
  |>.compose (txt "1.0 release" 16 true teal |>.translate 430 (-128))
  |>.compose (txt "Sep 2026" 14 true muted |>.translate (-430) (-165))
  |>.compose (txt "Dec 2026" 14 true muted |>.translate 430 (-165))
  |>.scale 0.9
```
:::
